dist: trusty
sudo: false
language: python
cache: pip
python:
  - "2.7"
  - "3.6"

# http://docs.travis-ci.com/user/customizing-the-build/#Git-Submodules
git:
  submodules: false

# command to install dependencies
install:
  - pip install -U pip
  - pip -q install -r requirements.txt
  - pip -q install "http://download.pytorch.org/whl/cu75/torch-0.2.0.post1-cp27-cp27mu-manylinux1_x86_64.whl; python_version == '2.7'"
  - pip -q install "http://download.pytorch.org/whl/cu75/torch-0.2.0.post1-cp36-cp36m-manylinux1_x86_64.whl; python_version == '3.6'"

  # dev dependencies
  - pip install flake8
  - pip install coverage

# command to run tests
before_script:
  # Syntax Checks
  # stop the build if there are Python syntax errors or undefined names
  - time flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
  # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
  - time flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  # https://github.com/travis-ci/travis-ci/issues/4099
  - git submodule update --init --remote --recursive


  # Prepare data for integration test
  - cd ibm-seq2seq
  - scripts/toy.sh

script: 
  # Unit test
  - nosetests --with-coverage --cover-erase --cover-package=ibm-seq2seq/seq2seq
  # Integration test
  - "if [[ $TRAVIS_BRANCH =~ (master|develop) ]]; then cd ibm-seq2seq && python setup.py install && scripts/integration_test.sh; fi"